"""
Generate imagenet_classes.json containing all 1000 ImageNet-1K classes
in the format "中文名 (English name)".
"""

import json
import os

# All 1000 ImageNet-1K classes with Chinese translations
IMAGENET_CLASSES = [
    "丁鲷 (tench)",
    "金鱼 (goldfish)",
    "大白鲨 (great white shark)",
    "虎鲨 (tiger shark)",
    "锤头鲨 (hammerhead)",
    "电鳐 (electric ray)",
    "黄貂鱼 (stingray)",
    "公鸡 (cock)",
    "母鸡 (hen)",
    "鸵鸟 (ostrich)",
    "燕雀 (brambling)",
    "金翅雀 (goldfinch)",
    "家朱雀 (house finch)",
    "灯草雀 (junco)",
    "靛蓝彩鹀 (indigo bunting)",
    "知更鸟 (robin)",
    "夜莺 (bulbul)",
    "松鸦 (jay)",
    "喜鹊 (magpie)",
    "山雀 (chickadee)",
    "河乌 (water ouzel)",
    "鸢 (kite)",
    "白头鹰 (bald eagle)",
    "秃鹫 (vulture)",
    "大灰猫头鹰 (great grey owl)",
    "欧洲火蝾螈 (European fire salamander)",
    "普通蝾螈 (common newt)",
    "水蜥 (eft)",
    "斑点蝾螈 (spotted salamander)",
    "美西螈 (axolotl)",
    "牛蛙 (bullfrog)",
    "树蛙 (tree frog)",
    "尾蛙 (tailed frog)",
    "蠵龟 (loggerhead)",
    "棱皮龟 (leatherback turtle)",
    "泥龟 (mud turtle)",
    "水龟 (terrapin)",
    "箱龟 (box turtle)",
    "环纹壁虎 (banded gecko)",
    "普通鬣蜥 (common iguana)",
    "美洲变色龙 (American chameleon)",
    "鞭尾蜥 (whiptail)",
    "鬃蜥 (agama)",
    "伞蜥 (frilled lizard)",
    "鳄蜥 (alligator lizard)",
    "希拉毒蜥 (Gila monster)",
    "绿蜥蜴 (green lizard)",
    "非洲变色龙 (African chameleon)",
    "科莫多龙 (Komodo dragon)",
    "非洲鳄鱼 (African crocodile)",
    "美洲短吻鳄 (American alligator)",
    "三角龙 (triceratops)",
    "雷蛇 (thunder snake)",
    "环颈蛇 (ringneck snake)",
    "猪鼻蛇 (hognose snake)",
    "绿蛇 (green snake)",
    "王蛇 (king snake)",
    "袜带蛇 (garter snake)",
    "水蛇 (water snake)",
    "藤蛇 (vine snake)",
    "夜蛇 (night snake)",
    "红尾蚺 (boa constrictor)",
    "岩蟒 (rock python)",
    "印度眼镜蛇 (Indian cobra)",
    "绿曼巴蛇 (green mamba)",
    "海蛇 (sea snake)",
    "角蝰 (horned viper)",
    "菱背响尾蛇 (diamondback)",
    "角响尾蛇 (sidewinder)",
    "三叶虫 (trilobite)",
    "盲蛛 (harvestman)",
    "蝎子 (scorpion)",
    "黑金园蛛 (black and gold garden spider)",
    "谷仓蜘蛛 (barn spider)",
    "园蛛 (garden spider)",
    "黑寡妇蜘蛛 (black widow)",
    "狼蛛 (tarantula)",
    "狼蛛科 (wolf spider)",
    "蜱虫 (tick)",
    "蜈蚣 (centipede)",
    "黑琴鸡 (black grouse)",
    "雷鸟 (ptarmigan)",
    "披肩鸡 (ruffed grouse)",
    "草原松鸡 (prairie chicken)",
    "孔雀 (peacock)",
    "鹌鹑 (quail)",
    "鹧鸪 (partridge)",
    "非洲灰鹦鹉 (African grey)",
    "金刚鹦鹉 (macaw)",
    "葵花凤头鹦鹉 (sulphur-crested cockatoo)",
    "吸蜜鹦鹉 (lorikeet)",
    "褐翅鸦鹃 (coucal)",
    "蜂虎 (bee eater)",
    "犀鸟 (hornbill)",
    "蜂鸟 (hummingbird)",
    "鹟䴕 (jacamar)",
    "巨嘴鸟 (toucan)",
    "公鸭 (drake)",
    "红胸秋沙鸭 (red-breasted merganser)",
    "鹅 (goose)",
    "黑天鹅 (black swan)",
    "大象 (tusker)",
    "针鼹 (echidna)",
    "鸭嘴兽 (platypus)",
    "沙袋鼠 (wallaby)",
    "考拉 (koala)",
    "袋熊 (wombat)",
    "水母 (jellyfish)",
    "海葵 (sea anemone)",
    "脑珊瑚 (brain coral)",
    "扁虫 (flatworm)",
    "线虫 (nematode)",
    "海螺 (conch)",
    "蜗牛 (snail)",
    "蛞蝓 (slug)",
    "海蛞蝓 (sea slug)",
    "石鳖 (chiton)",
    "鹦鹉螺 (chambered nautilus)",
    "珍宝蟹 (Dungeness crab)",
    "岩蟹 (rock crab)",
    "招潮蟹 (fiddler crab)",
    "帝王蟹 (king crab)",
    "美洲龙虾 (American lobster)",
    "刺龙虾 (spiny lobster)",
    "小龙虾 (crayfish)",
    "寄居蟹 (hermit crab)",
    "等足类 (isopod)",
    "白鹳 (white stork)",
    "黑鹳 (black stork)",
    "琵鹭 (spoonbill)",
    "火烈鸟 (flamingo)",
    "小蓝鹭 (little blue heron)",
    "美洲白鹭 (American egret)",
    "麻鸦 (bittern)",
    "鹤 (crane)",
    "秧鹤 (limpkin)",
    "欧洲水鸡 (European gallinule)",
    "美洲骨顶 (American coot)",
    "鸨 (bustard)",
    "翻石鹬 (ruddy turnstone)",
    "红背滨鹬 (red-backed sandpiper)",
    "红脚鹬 (redshank)",
    "长嘴半蹼鹬 (dowitcher)",
    "蛎鹬 (oystercatcher)",
    "鹈鹕 (pelican)",
    "国王企鹅 (king penguin)",
    "信天翁 (albatross)",
    "灰鲸 (grey whale)",
    "虎鲸 (killer whale)",
    "儒艮 (dugong)",
    "海狮 (sea lion)",
    "吉娃娃 (Chihuahua)",
    "日本狆 (Japanese spaniel)",
    "马尔济斯犬 (Maltese dog)",
    "京巴犬 (Pekinese)",
    "西施犬 (Shih-Tzu)",
    "布伦海姆獚 (Blenheim spaniel)",
    "蝴蝶犬 (papillon)",
    "玩具梗 (toy terrier)",
    "罗得西亚脊背犬 (Rhodesian ridgeback)",
    "阿富汗猎犬 (Afghan hound)",
    "巴吉度猎犬 (basset)",
    "比格犬 (beagle)",
    "寻血猎犬 (bloodhound)",
    "蓝斑猎犬 (bluetick)",
    "黑褐猎浣熊犬 (black-and-tan coonhound)",
    "沃克猎犬 (Walker hound)",
    "英国猎狐犬 (English foxhound)",
    "红骨猎犬 (redbone)",
    "俄罗斯猎狼犬 (borzoi)",
    "爱尔兰猎狼犬 (Irish wolfhound)",
    "意大利灵缇 (Italian greyhound)",
    "惠比特犬 (whippet)",
    "伊比赞猎犬 (Ibizan hound)",
    "挪威猎麋犬 (Norwegian elkhound)",
    "猎水獭犬 (otterhound)",
    "萨路基猎犬 (Saluki)",
    "苏格兰猎鹿犬 (Scottish deerhound)",
    "魏玛犬 (Weimaraner)",
    "斯塔福郡斗牛梗 (Staffordshire bullterrier)",
    "美国斯塔福郡梗 (American Staffordshire terrier)",
    "贝灵顿梗 (Bedlington terrier)",
    "边境梗 (Border terrier)",
    "凯利蓝梗 (Kerry blue terrier)",
    "爱尔兰梗 (Irish terrier)",
    "诺福克梗 (Norfolk terrier)",
    "诺维奇梗 (Norwich terrier)",
    "约克夏梗 (Yorkshire terrier)",
    "硬毛猎狐梗 (wire-haired fox terrier)",
    "湖畔梗 (Lakeland terrier)",
    "西里汉梗 (Sealyham terrier)",
    "万能梗 (Airedale)",
    "凯恩梗 (cairn)",
    "澳大利亚梗 (Australian terrier)",
    "丹迪丁蒙梗 (Dandie Dinmont)",
    "波士顿梗 (Boston bull)",
    "迷你雪纳瑞 (miniature schnauzer)",
    "巨型雪纳瑞 (giant schnauzer)",
    "标准雪纳瑞 (standard schnauzer)",
    "苏格兰梗 (Scotch terrier)",
    "西藏梗 (Tibetan terrier)",
    "丝毛梗 (silky terrier)",
    "软毛麦色梗 (soft-coated wheaten terrier)",
    "西高地白梗 (West Highland white terrier)",
    "拉萨犬 (Lhasa)",
    "平毛寻回犬 (flat-coated retriever)",
    "卷毛寻回犬 (curly-coated retriever)",
    "金毛寻回犬 (golden retriever)",
    "拉布拉多寻回犬 (Labrador retriever)",
    "切萨皮克湾寻回犬 (Chesapeake Bay retriever)",
    "德国短毛指示犬 (German short-haired pointer)",
    "维兹拉犬 (vizsla)",
    "英国塞特犬 (English setter)",
    "爱尔兰塞特犬 (Irish setter)",
    "戈登塞特犬 (Gordon setter)",
    "布列塔尼獚 (Brittany spaniel)",
    "克伦伯獚 (clumber)",
    "英国史宾格犬 (English springer)",
    "威尔士史宾格獚 (Welsh springer spaniel)",
    "可卡獚 (cocker spaniel)",
    "苏塞克斯獚 (Sussex spaniel)",
    "爱尔兰水獚 (Irish water spaniel)",
    "库瓦兹犬 (kuvasz)",
    "史奇派克犬 (schipperke)",
    "格罗安达犬 (groenendael)",
    "马林诺斯犬 (malinois)",
    "布里犬 (briard)",
    "卡尔比犬 (kelpie)",
    "可蒙犬 (komondor)",
    "古代英国牧羊犬 (Old English sheepdog)",
    "喜乐蒂牧羊犬 (Shetland sheepdog)",
    "柯利牧羊犬 (collie)",
    "边境牧羊犬 (Border collie)",
    "法兰德斯牧牛犬 (Bouvier des Flandres)",
    "罗威纳犬 (Rottweiler)",
    "德国牧羊犬 (German shepherd)",
    "杜宾犬 (Doberman)",
    "迷你品犬 (miniature pinscher)",
    "大瑞士山地犬 (Greater Swiss Mountain dog)",
    "伯恩山犬 (Bernese mountain dog)",
    "阿彭策尔牧牛犬 (Appenzeller)",
    "恩特雷布赫牧牛犬 (EntleBucher)",
    "拳师犬 (boxer)",
    "斗牛獒 (bull mastiff)",
    "藏獒 (Tibetan mastiff)",
    "法国斗牛犬 (French bulldog)",
    "大丹犬 (Great Dane)",
    "圣伯纳犬 (Saint Bernard)",
    "爱斯基摩犬 (Eskimo dog)",
    "阿拉斯加雪橇犬 (malamute)",
    "西伯利亚雪橇犬 (Siberian husky)",
    "斑点犬 (dalmatian)",
    "猴面犬 (affenpinscher)",
    "巴仙吉犬 (basenji)",
    "巴哥犬 (pug)",
    "莱昂贝格犬 (Leonberg)",
    "纽芬兰犬 (Newfoundland)",
    "大白熊犬 (Great Pyrenees)",
    "萨摩耶犬 (Samoyed)",
    "博美犬 (Pomeranian)",
    "松狮犬 (chow)",
    "荷兰毛狮犬 (keeshond)",
    "布鲁塞尔格里芬犬 (Brabancon griffon)",
    "彭布罗克威尔士柯基犬 (Pembroke)",
    "卡迪根威尔士柯基犬 (Cardigan)",
    "玩具贵宾犬 (toy poodle)",
    "迷你贵宾犬 (miniature poodle)",
    "标准贵宾犬 (standard poodle)",
    "墨西哥无毛犬 (Mexican hairless)",
    "灰狼 (timber wolf)",
    "白狼 (white wolf)",
    "红狼 (red wolf)",
    "郊狼 (coyote)",
    "澳洲野犬 (dingo)",
    "豺 (dhole)",
    "非洲野犬 (African hunting dog)",
    "鬣狗 (hyena)",
    "赤狐 (red fox)",
    "敏狐 (kit fox)",
    "北极狐 (Arctic fox)",
    "灰狐 (grey fox)",
    "虎斑猫 (tabby)",
    "虎猫 (tiger cat)",
    "波斯猫 (Persian cat)",
    "暹罗猫 (Siamese cat)",
    "埃及猫 (Egyptian cat)",
    "美洲狮 (cougar)",
    "猞猁 (lynx)",
    "豹 (leopard)",
    "雪豹 (snow leopard)",
    "美洲豹 (jaguar)",
    "狮子 (lion)",
    "老虎 (tiger)",
    "猎豹 (cheetah)",
    "棕熊 (brown bear)",
    "美洲黑熊 (American black bear)",
    "北极熊 (ice bear)",
    "懒熊 (sloth bear)",
    "猫鼬 (mongoose)",
    "狐獴 (meerkat)",
    "虎甲虫 (tiger beetle)",
    "瓢虫 (ladybug)",
    "步甲 (ground beetle)",
    "天牛 (long-horned beetle)",
    "叶甲 (leaf beetle)",
    "蜣螂 (dung beetle)",
    "犀牛甲虫 (rhinoceros beetle)",
    "象鼻虫 (weevil)",
    "苍蝇 (fly)",
    "蜜蜂 (bee)",
    "蚂蚁 (ant)",
    "蚱蜢 (grasshopper)",
    "蟋蟀 (cricket)",
    "竹节虫 (walking stick)",
    "蟑螂 (cockroach)",
    "螳螂 (mantis)",
    "蝉 (cicada)",
    "叶蝉 (leafhopper)",
    "草蛉 (lacewing)",
    "蜻蜓 (dragonfly)",
    "豆娘 (damselfly)",
    "蛱蝶 (admiral)",
    "环蝶 (ringlet)",
    "君主斑蝶 (monarch)",
    "菜粉蝶 (cabbage butterfly)",
    "黄粉蝶 (sulphur butterfly)",
    "灰蝶 (lycaenid)",
    "海星 (starfish)",
    "海胆 (sea urchin)",
    "海参 (sea cucumber)",
    "林兔 (wood rabbit)",
    "野兔 (hare)",
    "安哥拉兔 (Angora)",
    "仓鼠 (hamster)",
    "豪猪 (porcupine)",
    "狐松鼠 (fox squirrel)",
    "旱獭 (marmot)",
    "河狸 (beaver)",
    "豚鼠 (guinea pig)",
    "栗色马 (sorrel)",
    "斑马 (zebra)",
    "猪 (hog)",
    "野猪 (wild boar)",
    "疣猪 (warthog)",
    "河马 (hippopotamus)",
    "牛 (ox)",
    "水牛 (water buffalo)",
    "野牛 (bison)",
    "公羊 (ram)",
    "大角羊 (bighorn)",
    "北山羊 (ibex)",
    "麋羚 (hartebeest)",
    "黑斑羚 (impala)",
    "瞪羚 (gazelle)",
    "阿拉伯骆驼 (Arabian camel)",
    "羊驼 (llama)",
    "黄鼠狼 (weasel)",
    "水貂 (mink)",
    "艾鼬 (polecat)",
    "黑足鼬 (black-footed ferret)",
    "水獭 (otter)",
    "臭鼬 (skunk)",
    "獾 (badger)",
    "犰狳 (armadillo)",
    "三趾树懒 (three-toed sloth)",
    "猩猩 (orangutan)",
    "大猩猩 (gorilla)",
    "黑猩猩 (chimpanzee)",
    "长臂猿 (gibbon)",
    "合趾猿 (siamang)",
    "长尾猴 (guenon)",
    "赤猴 (patas)",
    "狒狒 (baboon)",
    "猕猴 (macaque)",
    "叶猴 (langur)",
    "疣猴 (colobus)",
    "长鼻猴 (proboscis monkey)",
    "狨猴 (marmoset)",
    "卷尾猴 (capuchin)",
    "吼猴 (howler monkey)",
    "伶猴 (titi)",
    "蜘蛛猴 (spider monkey)",
    "松鼠猴 (squirrel monkey)",
    "马达加斯加猫 (Madagascar cat)",
    "大狐猴 (indri)",
    "印度象 (Indian elephant)",
    "非洲象 (African elephant)",
    "小熊猫 (lesser panda)",
    "大熊猫 (giant panda)",
    "蛇鲭 (barracouta)",
    "鳗鱼 (eel)",
    "银大马哈鱼 (coho)",
    "岩美鱼 (rock beauty)",
    "海葵鱼 (anemone fish)",
    "鲟鱼 (sturgeon)",
    "雀鳝 (gar)",
    "狮子鱼 (lionfish)",
    "河豚 (puffer)",
    "算盘 (abacus)",
    "阿拉伯长袍 (abaya)",
    "学士袍 (academic gown)",
    "手风琴 (accordion)",
    "原声吉他 (acoustic guitar)",
    "航空母舰 (aircraft carrier)",
    "客机 (airliner)",
    "飞艇 (airship)",
    "祭坛 (altar)",
    "救护车 (ambulance)",
    "两栖车辆 (amphibian)",
    "指针时钟 (analog clock)",
    "蜂房 (apiary)",
    "围裙 (apron)",
    "垃圾桶 (ashcan)",
    "突击步枪 (assault rifle)",
    "背包 (backpack)",
    "面包店 (bakery)",
    "平衡木 (balance beam)",
    "气球 (balloon)",
    "圆珠笔 (ballpoint)",
    "创可贴 (Band Aid)",
    "班卓琴 (banjo)",
    "栏杆 (bannister)",
    "杠铃 (barbell)",
    "理发椅 (barber chair)",
    "理发店 (barbershop)",
    "谷仓 (barn)",
    "气压计 (barometer)",
    "桶 (barrel)",
    "手推车 (barrow)",
    "棒球 (baseball)",
    "篮球 (basketball)",
    "婴儿摇篮 (bassinet)",
    "巴松管 (bassoon)",
    "浴帽 (bathing cap)",
    "浴巾 (bath towel)",
    "浴缸 (bathtub)",
    "沙滩车 (beach wagon)",
    "灯塔 (beacon)",
    "烧杯 (beaker)",
    "熊皮帽 (bearskin)",
    "啤酒瓶 (beer bottle)",
    "啤酒杯 (beer glass)",
    "钟楼 (bell cote)",
    "围嘴 (bib)",
    "双人自行车 (bicycle-built-for-two)",
    "比基尼 (bikini)",
    "活页夹 (binder)",
    "双筒望远镜 (binoculars)",
    "鸟舍 (birdhouse)",
    "船库 (boathouse)",
    "雪橇 (bobsled)",
    "波洛领带 (bolo tie)",
    "软帽 (bonnet)",
    "书柜 (bookcase)",
    "书店 (bookshop)",
    "瓶盖 (bottlecap)",
    "弓 (bow)",
    "领结 (bow tie)",
    "铜牌 (brass)",
    "文胸 (brassiere)",
    "防波堤 (breakwater)",
    "胸甲 (breastplate)",
    "扫帚 (broom)",
    "水桶 (bucket)",
    "带扣 (buckle)",
    "防弹背心 (bulletproof vest)",
    "高铁 (bullet train)",
    "肉铺 (butcher shop)",
    "出租车 (cab)",
    "大锅 (caldron)",
    "蜡烛 (candle)",
    "大炮 (cannon)",
    "独木舟 (canoe)",
    "开罐器 (can opener)",
    "开襟毛衣 (cardigan)",
    "汽车后视镜 (car mirror)",
    "旋转木马 (carousel)",
    "木工工具 (carpenter's kit)",
    "纸箱 (carton)",
    "车轮 (car wheel)",
    "取款机 (cash machine)",
    "磁带 (cassette)",
    "磁带播放器 (cassette player)",
    "城堡 (castle)",
    "双体船 (catamaran)",
    "CD播放器 (CD player)",
    "大提琴 (cello)",
    "手机 (cellular telephone)",
    "链条 (chain)",
    "铁丝网围栏 (chainlink fence)",
    "锁子甲 (chain mail)",
    "链锯 (chain saw)",
    "箱子 (chest)",
    "五斗柜 (chiffonier)",
    "钟琴 (chime)",
    "瓷器柜 (china cabinet)",
    "圣诞袜 (Christmas stocking)",
    "教堂 (church)",
    "电影院 (cinema)",
    "切肉刀 (cleaver)",
    "悬崖住所 (cliff dwelling)",
    "斗篷 (cloak)",
    "木屐 (clog)",
    "调酒器 (cocktail shaker)",
    "咖啡杯 (coffee mug)",
    "咖啡壶 (coffeepot)",
    "线圈 (coil)",
    "密码锁 (combination lock)",
    "电脑键盘 (computer keyboard)",
    "糖果店 (confectionery)",
    "集装箱船 (container ship)",
    "敞篷车 (convertible)",
    "开瓶器 (corkscrew)",
    "短号 (cornet)",
    "牛仔靴 (cowboy boot)",
    "牛仔帽 (cowboy hat)",
    "摇篮 (cradle)",
    "起重机 (crane)",
    "安全头盔 (crash helmet)",
    "板条箱 (crate)",
    "婴儿床 (crib)",
    "慢炖锅 (Crock Pot)",
    "槌球 (croquet ball)",
    "拐杖 (crutch)",
    "胸甲 (cuirass)",
    "水坝 (dam)",
    "书桌 (desk)",
    "台式电脑 (desktop computer)",
    "拨号电话 (dial telephone)",
    "尿布 (diaper)",
    "数字时钟 (digital clock)",
    "电子手表 (digital watch)",
    "餐桌 (dining table)",
    "抹布 (dishrag)",
    "洗碗机 (dishwasher)",
    "盘式制动器 (disk brake)",
    "码头 (dock)",
    "狗拉雪橇 (dogsled)",
    "穹顶 (dome)",
    "门垫 (doormat)",
    "钻井平台 (drilling platform)",
    "鼓 (drum)",
    "鼓槌 (drumstick)",
    "哑铃 (dumbbell)",
    "荷兰锅 (Dutch oven)",
    "电风扇 (electric fan)",
    "电吉他 (electric guitar)",
    "电力机车 (electric locomotive)",
    "娱乐中心 (entertainment center)",
    "信封 (envelope)",
    "意式咖啡机 (espresso maker)",
    "粉饼 (face powder)",
    "羽毛围巾 (feather boa)",
    "文件柜 (file)",
    "消防船 (fireboat)",
    "消防车 (fire engine)",
    "防火屏 (fire screen)",
    "旗杆 (flagpole)",
    "长笛 (flute)",
    "折叠椅 (folding chair)",
    "橄榄球头盔 (football helmet)",
    "叉车 (forklift)",
    "喷泉 (fountain)",
    "钢笔 (fountain pen)",
    "四柱床 (four-poster)",
    "货车车厢 (freight car)",
    "圆号 (French horn)",
    "煎锅 (frying pan)",
    "毛皮大衣 (fur coat)",
    "垃圾车 (garbage truck)",
    "防毒面具 (gasmask)",
    "加油泵 (gas pump)",
    "高脚杯 (goblet)",
    "卡丁车 (go-kart)",
    "高尔夫球 (golf ball)",
    "高尔夫球车 (golfcart)",
    "贡多拉 (gondola)",
    "锣 (gong)",
    "礼服 (gown)",
    "三角钢琴 (grand piano)",
    "温室 (greenhouse)",
    "格栅 (grille)",
    "杂货店 (grocery store)",
    "断头台 (guillotine)",
    "发夹 (hair slide)",
    "发胶 (hair spray)",
    "半履带车 (half track)",
    "锤子 (hammer)",
    "脏衣篮 (hamper)",
    "吹风机 (hand blower)",
    "手持电脑 (hand-held computer)",
    "手帕 (handkerchief)",
    "硬盘 (hard disc)",
    "口琴 (harmonica)",
    "竖琴 (harp)",
    "收割机 (harvester)",
    "短柄斧 (hatchet)",
    "枪套 (holster)",
    "家庭影院 (home theater)",
    "蜂巢 (honeycomb)",
    "钩子 (hook)",
    "箍裙 (hoopskirt)",
    "单杠 (horizontal bar)",
    "马车 (horse cart)",
    "沙漏 (hourglass)",
    "iPod (iPod)",
    "熨斗 (iron)",
    "南瓜灯 (jack-o'-lantern)",
    "牛仔裤 (jean)",
    "吉普车 (jeep)",
    "运动衫 (jersey)",
    "拼图 (jigsaw puzzle)",
    "人力车 (jinrikisha)",
    "操纵杆 (joystick)",
    "和服 (kimono)",
    "护膝 (knee pad)",
    "绳结 (knot)",
    "实验室外套 (lab coat)",
    "长柄勺 (ladle)",
    "灯罩 (lampshade)",
    "笔记本电脑 (laptop)",
    "割草机 (lawn mower)",
    "镜头盖 (lens cap)",
    "开信刀 (letter opener)",
    "图书馆 (library)",
    "救生艇 (lifeboat)",
    "打火机 (lighter)",
    "豪华轿车 (limousine)",
    "邮轮 (liner)",
    "口红 (lipstick)",
    "乐福鞋 (Loafer)",
    "乳液 (lotion)",
    "扬声器 (loudspeaker)",
    "放大镜 (loupe)",
    "锯木厂 (lumbermill)",
    "指南针 (magnetic compass)",
    "邮袋 (mailbag)",
    "邮箱 (mailbox)",
    "紧身体操服 (maillot)",
    "泳衣 (maillot)",
    "井盖 (manhole cover)",
    "沙锤 (maraca)",
    "马林巴琴 (marimba)",
    "面具 (mask)",
    "火柴 (matchstick)",
    "五月柱 (maypole)",
    "迷宫 (maze)",
    "量杯 (measuring cup)",
    "药箱 (medicine chest)",
    "巨石 (megalith)",
    "麦克风 (microphone)",
    "微波炉 (microwave)",
    "军装 (military uniform)",
    "牛奶罐 (milk can)",
    "小巴 (minibus)",
    "迷你裙 (miniskirt)",
    "小型货车 (minivan)",
    "导弹 (missile)",
    "连指手套 (mitten)",
    "搅拌碗 (mixing bowl)",
    "移动房屋 (mobile home)",
    "T型车 (Model T)",
    "调制解调器 (modem)",
    "修道院 (monastery)",
    "显示器 (monitor)",
    "轻便摩托车 (moped)",
    "砂浆 (mortar)",
    "学位帽 (mortarboard)",
    "清真寺 (mosque)",
    "蚊帐 (mosquito net)",
    "摩托车 (motor scooter)",
    "山地自行车 (mountain bike)",
    "登山帐篷 (mountain tent)",
    "鼠标 (mouse)",
    "捕鼠器 (mousetrap)",
    "搬家货车 (moving van)",
    "口套 (muzzle)",
    "钉子 (nail)",
    "颈托 (neck brace)",
    "项链 (necklace)",
    "奶嘴 (nipple)",
    "笔记本 (notebook)",
    "方尖碑 (obelisk)",
    "双簧管 (oboe)",
    "陶笛 (ocarina)",
    "里程表 (odometer)",
    "机油滤清器 (oil filter)",
    "风琴 (organ)",
    "示波器 (oscilloscope)",
    "罩裙 (overskirt)",
    "牛车 (oxcart)",
    "氧气面罩 (oxygen mask)",
    "包装袋 (packet)",
    "船桨 (paddle)",
    "明轮船 (paddlewheel)",
    "挂锁 (padlock)",
    "画笔 (paintbrush)",
    "睡衣 (pajama)",
    "宫殿 (palace)",
    "排箫 (panpipe)",
    "纸巾 (paper towel)",
    "降落伞 (parachute)",
    "双杠 (parallel bars)",
    "公园长椅 (park bench)",
    "停车计时器 (parking meter)",
    "客车 (passenger car)",
    "露台 (patio)",
    "公用电话 (pay-phone)",
    "基座 (pedestal)",
    "铅笔盒 (pencil box)",
    "卷笔刀 (pencil sharpener)",
    "香水 (perfume)",
    "培养皿 (Petri dish)",
    "复印机 (photocopier)",
    "拨片 (pick)",
    "尖顶头盔 (pickelhaube)",
    "尖桩篱笆 (picket fence)",
    "皮卡车 (pickup)",
    "码头 (pier)",
    "存钱罐 (piggy bank)",
    "药瓶 (pill bottle)",
    "枕头 (pillow)",
    "乒乓球 (ping-pong ball)",
    "风车 (pinwheel)",
    "海盗船 (pirate)",
    "水罐 (pitcher)",
    "刨子 (plane)",
    "天文馆 (planetarium)",
    "塑料袋 (plastic bag)",
    "碗碟架 (plate rack)",
    "犁 (plow)",
    "搋子 (plunger)",
    "拍立得相机 (Polaroid camera)",
    "杆 (pole)",
    "警车 (police van)",
    "雨披 (poncho)",
    "台球桌 (pool table)",
    "汽水瓶 (pop bottle)",
    "花盆 (pot)",
    "陶轮 (potter's wheel)",
    "电钻 (power drill)",
    "祈祷毯 (prayer rug)",
    "打印机 (printer)",
    "监狱 (prison)",
    "炮弹 (projectile)",
    "投影仪 (projector)",
    "冰球 (puck)",
    "沙袋 (punching bag)",
    "手提包 (purse)",
    "羽毛笔 (quill)",
    "被子 (quilt)",
    "赛车 (racer)",
    "球拍 (racket)",
    "散热器 (radiator)",
    "收音机 (radio)",
    "射电望远镜 (radio telescope)",
    "雨水桶 (rain barrel)",
    "房车 (recreational vehicle)",
    "卷轴 (reel)",
    "反光照相机 (reflex camera)",
    "冰箱 (refrigerator)",
    "遥控器 (remote control)",
    "餐厅 (restaurant)",
    "左轮手枪 (revolver)",
    "步枪 (rifle)",
    "摇椅 (rocking chair)",
    "烤肉架 (rotisserie)",
    "橡皮擦 (rubber eraser)",
    "橄榄球 (rugby ball)",
    "尺子 (rule)",
    "跑鞋 (running shoe)",
    "保险箱 (safe)",
    "安全别针 (safety pin)",
    "盐瓶 (saltshaker)",
    "凉鞋 (sandal)",
    "纱笼 (sarong)",
    "萨克斯 (sax)",
    "剑鞘 (scabbard)",
    "秤 (scale)",
    "校车 (school bus)",
    "帆船 (schooner)",
    "记分板 (scoreboard)",
    "屏幕 (screen)",
    "螺丝 (screw)",
    "螺丝刀 (screwdriver)",
    "安全带 (seat belt)",
    "缝纫机 (sewing machine)",
    "盾牌 (shield)",
    "鞋店 (shoe shop)",
    "障子 (shoji)",
    "购物篮 (shopping basket)",
    "购物车 (shopping cart)",
    "铲子 (shovel)",
    "浴帽 (shower cap)",
    "浴帘 (shower curtain)",
    "滑雪板 (ski)",
    "滑雪面罩 (ski mask)",
    "睡袋 (sleeping bag)",
    "计算尺 (slide rule)",
    "推拉门 (sliding door)",
    "老虎机 (slot)",
    "通气管 (snorkel)",
    "雪地摩托 (snowmobile)",
    "扫雪机 (snowplow)",
    "皂液器 (soap dispenser)",
    "足球 (soccer ball)",
    "袜子 (sock)",
    "太阳能碟 (solar dish)",
    "墨西哥宽边帽 (sombrero)",
    "汤碗 (soup bowl)",
    "空格键 (space bar)",
    "空间加热器 (space heater)",
    "航天飞机 (space shuttle)",
    "锅铲 (spatula)",
    "快艇 (speedboat)",
    "蜘蛛网 (spider web)",
    "纺锤 (spindle)",
    "跑车 (sports car)",
    "聚光灯 (spotlight)",
    "舞台 (stage)",
    "蒸汽机车 (steam locomotive)",
    "钢拱桥 (steel arch bridge)",
    "钢鼓 (steel drum)",
    "听诊器 (stethoscope)",
    "圣带 (stole)",
    "石墙 (stone wall)",
    "秒表 (stopwatch)",
    "炉子 (stove)",
    "滤网 (strainer)",
    "担架 (stretcher)",
    "沙发床 (studio couch)",
    "佛塔 (stupa)",
    "潜艇 (submarine)",
    "西装 (suit)",
    "日晷 (sundial)",
    "太阳镜 (sunglass)",
    "墨镜 (sunglasses)",
    "防晒霜 (sunscreen)",
    "悬索桥 (suspension bridge)",
    "拖把 (swab)",
    "运动衫 (sweatshirt)",
    "泳裤 (swimming trunks)",
    "秋千 (swing)",
    "开关 (switch)",
    "注射器 (syringe)",
    "台灯 (table lamp)",
    "坦克 (tank)",
    "磁带播放器 (tape player)",
    "茶壶 (teapot)",
    "泰迪熊 (teddy)",
    "电视 (television)",
    "网球 (tennis ball)",
    "茅草屋顶 (thatch)",
    "剧院幕布 (theater curtain)",
    "顶针 (thimble)",
    "脱粒机 (thresher)",
    "宝座 (throne)",
    "瓦屋顶 (tile roof)",
    "烤面包机 (toaster)",
    "烟草店 (tobacco shop)",
    "马桶座 (toilet seat)",
    "火炬 (torch)",
    "图腾柱 (totem pole)",
    "拖车 (tow truck)",
    "玩具店 (toyshop)",
    "拖拉机 (tractor)",
    "拖挂卡车 (trailer truck)",
    "托盘 (tray)",
    "风衣 (trench coat)",
    "三轮车 (tricycle)",
    "三体船 (trimaran)",
    "三脚架 (tripod)",
    "凯旋门 (triumphal arch)",
    "无轨电车 (trolleybus)",
    "长号 (trombone)",
    "木盆 (tub)",
    "旋转闸门 (turnstile)",
    "打字机键盘 (typewriter keyboard)",
    "雨伞 (umbrella)",
    "独轮车 (unicycle)",
    "立式钢琴 (upright)",
    "吸尘器 (vacuum)",
    "花瓶 (vase)",
    "拱顶 (vault)",
    "天鹅绒 (velvet)",
    "自动售货机 (vending machine)",
    "法衣 (vestment)",
    "高架桥 (viaduct)",
    "小提琴 (violin)",
    "排球 (volleyball)",
    "华夫饼机 (waffle iron)",
    "挂钟 (wall clock)",
    "钱包 (wallet)",
    "衣柜 (wardrobe)",
    "战机 (warplane)",
    "洗手盆 (washbasin)",
    "洗衣机 (washer)",
    "水瓶 (water bottle)",
    "水壶 (water jug)",
    "水塔 (water tower)",
    "威士忌酒壶 (whiskey jug)",
    "哨子 (whistle)",
    "假发 (wig)",
    "纱窗 (window screen)",
    "窗帘 (window shade)",
    "温莎领带 (Windsor tie)",
    "酒瓶 (wine bottle)",
    "机翼 (wing)",
    "炒锅 (wok)",
    "木勺 (wooden spoon)",
    "羊毛 (wool)",
    "蜿蜒栅栏 (worm fence)",
    "沉船 (wreck)",
    "双桅帆船 (yawl)",
    "蒙古包 (yurt)",
    "网站 (web site)",
    "漫画书 (comic book)",
    "填字游戏 (crossword puzzle)",
    "路标 (street sign)",
    "交通信号灯 (traffic light)",
    "书皮 (book jacket)",
    "菜单 (menu)",
    "盘子 (plate)",
    "鳄梨酱 (guacamole)",
    "清汤 (consomme)",
    "火锅 (hot pot)",
    "松糕 (trifle)",
    "冰淇淋 (ice cream)",
    "冰棍 (ice lolly)",
    "法式面包 (French loaf)",
    "百吉饼 (bagel)",
    "椒盐卷饼 (pretzel)",
    "芝士汉堡 (cheeseburger)",
    "热狗 (hotdog)",
    "土豆泥 (mashed potato)",
    "卷心菜 (head cabbage)",
    "西兰花 (broccoli)",
    "花椰菜 (cauliflower)",
    "西葫芦 (zucchini)",
    "金丝瓜 (spaghetti squash)",
    "橡子南瓜 (acorn squash)",
    "冬南瓜 (butternut squash)",
    "黄瓜 (cucumber)",
    "洋蓟 (artichoke)",
    "甜椒 (bell pepper)",
    "刺菜蓟 (cardoon)",
    "蘑菇 (mushroom)",
    "青苹果 (Granny Smith)",
    "草莓 (strawberry)",
    "橙子 (orange)",
    "柠檬 (lemon)",
    "无花果 (fig)",
    "菠萝 (pineapple)",
    "香蕉 (banana)",
    "菠萝蜜 (jackfruit)",
    "番荔枝 (custard apple)",
    "石榴 (pomegranate)",
    "干草 (hay)",
    "培根蛋酱意面 (carbonara)",
    "巧克力酱 (chocolate sauce)",
    "面团 (dough)",
    "肉饼 (meat loaf)",
    "披萨 (pizza)",
    "派 (potpie)",
    "墨西哥卷饼 (burrito)",
    "红酒 (red wine)",
    "浓缩咖啡 (espresso)",
    "杯子 (cup)",
    "蛋奶酒 (eggnog)",
    "高山 (alp)",
    "气泡 (bubble)",
    "悬崖 (cliff)",
    "珊瑚礁 (coral reef)",
    "间歇泉 (geyser)",
    "湖边 (lakeside)",
    "海角 (promontory)",
    "沙洲 (sandbar)",
    "海滨 (seashore)",
    "山谷 (valley)",
    "火山 (volcano)",
    "棒球运动员 (ballplayer)",
    "新郎 (groom)",
    "潜水员 (scuba diver)",
    "油菜花 (rapeseed)",
    "雏菊 (daisy)",
    "黄杓兰 (yellow lady's slipper)",
    "玉米 (corn)",
    "橡子 (acorn)",
    "蔷薇果 (hip)",
    "七叶树果 (buckeye)",
    "珊瑚菌 (coral fungus)",
    "伞菌 (agaric)",
    "鹿花菌 (gyromitra)",
    "鬼笔菌 (stinkhorn)",
    "地星菌 (earthstar)",
    "灰树花菌 (hen-of-the-woods)",
    "牛肝菌 (bolete)",
    "玉米穗 (ear)",
    "卫生纸 (toilet tissue)",
    "湖畔 (lakeside)",
]

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "routes")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "imagenet_classes.json")


def main():
    assert len(IMAGENET_CLASSES) == 1000, (
        f"Expected 1000 classes, got {len(IMAGENET_CLASSES)}"
    )

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(IMAGENET_CLASSES, f, ensure_ascii=False, indent=2)

    print(f"Generated {OUTPUT_FILE} with {len(IMAGENET_CLASSES)} entries.")


if __name__ == "__main__":
    main()